image: tiangolo/docker-with-compose
stages:
  - check_docker_exist
  - build_image
  - push
  - push_version
  - coverage
  - update_k8s

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


check_docker_exist:
  tags:
    - docker
    - linux
  stage: check_docker_exist
  script:
    - docker info

build_image:
  tags:
    - docker
    - linux
  stage: build_image
  script:
    - docker build . -t docker.idiap.ch/wenet/wenet-realtime
coverage:
  image: docker.idiap.ch/wenet/wenet-realtime
  tags:
    - docker
    - linux
  stage: coverage
  script:
    - ./run_tests.sh
  artifacts:
    reports:
      cobertura: coverage.xml

push:
  tags:
    - docker
    - linux
  stage: push
  only:
    - master
  script:
    - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
    - docker push docker.idiap.ch/wenet/wenet-realtime:latest
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    - docker tag docker.idiap.ch/wenet/wenet-realtime:latest internetofus/wenet-realtime:latest
    - docker push internetofus/wenet-realtime:latest

push_version:
  tags:
    - docker
    - linux
  stage: push_version
  only:
    - tags
  script:
    - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
    - docker tag  docker.idiap.ch/wenet/wenet-realtime:latest docker.idiap.ch/wenet/wenet-realtime:$CI_COMMIT_TAG
    - docker push docker.idiap.ch/wenet/wenet-realtime:$CI_COMMIT_TAG
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    - docker tag docker.idiap.ch/wenet/wenet-realtime:$CI_COMMIT_TAG internetofus/wenet-realtime:$CI_COMMIT_TAG
    - docker push internetofus/wenet-realtime:$CI_COMMIT_TAG

update_k8s:
  tags:
    - docker
    - linux
  stage: update_k8s
  image: google/cloud-sdk
  retry: 2
  script:
    - mkdir -p $HOME/.kube
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - kubectl rollout restart deployment.apps/wenet-realtime-deployment
