  stages:
    - check_docker_exist
    - build_image
    - push
    - push_version
 
  check_docker_exist:
    stage: check_docker_exist
    script:
      - docker info
 
  build_image:
    stage: build_image
    script:
      - docker build . -t docker.idiap.ch/wenet/wenet-realtime
  push:
   stage: push
   only:
      - master
   script:
      - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
      - docker push docker.idiap.ch/wenet/wenet-realtime:latest
  push_version:
   stage: push_version
   only:
      - tags
   script:
      - echo $CI_JOB_TOKEN | docker login docker.idiap.ch -u gitlab-ci-token --password-stdin
      - docker tag  docker.idiap.ch/wenet/wenet-realtime:latest docker.idiap.ch/wenet/wenet-realtime:$CI_COMMIT_TAG
      - docker push docker.idiap.ch/wenet/wenet-realtime:$CI_COMMIT_TAG
 