apiVersion: apps/v1
kind: Deployment
metadata:
  name: wenet-realtime-deployment
  labels:
    app: wenet
spec:
  selector:
    matchLabels:
      app: wenet
  replicas: 1
  template:
    metadata:
      labels:
        app: wenet
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: settings-wenet-realtime-env
        name: wenet
        image: docker.idiap.ch/wenet/wenet-realtime:latest
        volumeMounts:
          - name: tz-zurich
            mountPath: /etc/localtime

        command: ["uvicorn"]
        args: ["--host", "0.0.0.0", "--timeout-keep-alive", "300", "--limit-max-requests", "5000", "--workers", "1", "--root-path", "/devel/hub/wenet", "wenet_realtime.app:app"]
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 10Gi
            #cpu: "2"
          requests:
            memory: 10Gi
            #cpu: "2"
      imagePullSecrets:
      - name: wenet-realtime-secret
      volumes:
      - name: tz-zurich
        hostPath:
          path: /usr/share/zoneinfo/Europe/Zurich

---

apiVersion: v1
data:
    VIRTUAL_HOST_LOCATION_WENET: /devel/hub/wenet
    VIRTUAL_LOCAL_PATH_WENET: /
    DEFAULT_LOG_FILE: /var/log/wenet.log
kind: ConfigMap
metadata:
    name: settings-wenet-realtime-env

---
apiVersion: v1
kind: Service
metadata:
  name: wenet
spec:
  selector:
    app: wenet
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: wenet
